train: ../train/images
val: ../valid/images
test: ../test/images

nc: 22
names: ['Cashew anthracnose', 'Cashew gumosis', 'Cashew healthy', 'Cashew leaf miner', 'Cashew red rust', 'Cassava bacterial blight', 'Cassava brown spot', 'Cassava green mite', 'Cassava healthy', 'Cassava mosaic', 'Maize fall armyworm', 'Maize grasshoper', 'Maize healthy', 'Maize leaf beetle', 'Maize leaf blight', 'Maize leaf spot', 'Maize streak virus', 'Tomato healthy', 'Tomato leaf blight', 'Tomato leaf curl', 'Tomato septoria leaf spot', 'Tomato verticulium wilt']

roboflow:
  workspace: yolo-plant-leave-test
  project: my-plant-project-hcmrp
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/yolo-plant-leave-test/my-plant-project-hcmrp/dataset/2